# filename setup
satellite_data_folder: data_satellite
saildrone_data_folder: data_saildrone
shapefile_data_folder: data_shapefile
scripts_folder: scripts
# satellite dataset setup - resolution should be rounded up
satellite_product: ASCAT
satellite_dataset_resolution: 0.3



# processing steps
create_dir_structure: False
register_dataset: False
convert_swath_outlines_to_shapefiles: True