# filename setup
satellite_data_folder: data_satellite
saildrone_data_folder: data_saildrone
shapefile_data_folder: data_shapefile
matching_data_folder: data_match
figure_data_folder: figs
log_data_folder: log
scripts_folder: scripts

# satellite dataset setup - resolution should be rounded up
satellite_product: ASCAT
satellite_variable_name: wind_speed

# saildrone setup
saildrone_year: 2022
saildrone_number: 1084
saildrone_time_tolerance_min: 2
saildrone_distance_tolerance_km: 50
saildrone_variable_name: wind_speed

# processing steps
create_dir_structure: True
register_dataset: True
match_saildrone_satellite_swaths: True
plot_saildrone_satellite_data_timeseries: True
plot_saildrone_satellite_data_scatter: True
plot_all_saildrones_scatter: True